### ISSUE TITLE
BUG: The docker return error

### ISSUE THREAD

**Issue by Editst** [tgbot-collection/SearchGram#20]
I use your docker config, it return error after I see `started xxx handlers`

```
[2022-06-12 23:30:01 dispatcher.py:253 E] mongo:27017: [Errno -2] Name does not resolve, Timeout: 5.0s, Topology Description: <TopologyDescription id: 62a60668753028ff637e85ee, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name does not resolve')>]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/searchgram/client.py", line 41, in message_handler
    tgdb.insert(data)
  File "/root/searchgram/engine.py", line 40, in insert
    resp = self.col.insert_one(doc)
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 606, in insert_one
    self._insert_one(
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 547, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1398, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1676, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1663, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1608, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 519, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 535, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 227, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name does not resolve, Timeout: 5.0s, Topology Description: <TopologyDescription id: 62a60668753028ff637e85ee, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name does not resolve')>]>
```

**Comment by BennyThink** [comment]
Do you have mongodb setup? This error message means it can't find mongodb.

If you're using docker-compose, the hostname should be `mongo`. If you're running the container with `docker run ...`, you should setup your own mongodb and use `-env` to specified it.

**Comment by Editst** [comment]
I use docker-compose and it woks, thanks.
