### ISSUE TITLE
几处小问题，几处改进建议

### ISSUE THREAD

**Issue by bennyzdog** [tgbot-collection/SearchGram#49]
- [x] 1. 目前同步消息的日志（可能还有其它日志）是通过 client 放在 Saved Message 里面的，既然已经在用 Bot 搜索了，建议通过 bot 发在用户与 Bot 的对话里

- [x] 2. 在 sync.ini 中填入 uid 报错，无法正常同步消息（日志中的 ID 已替换成 999999999）
```
Exception in thread Thread-1 (sync_history):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 148, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: 999999999'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 85, in resolve_peer
    return await self.storage.get_peer_by_phone_number(peer_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 174, in get_peer_by_phone_number
    raise KeyError(f"Phone number not found: {phone_number}")
KeyError: 'Phone number not found: 999999999'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/SearchGram/searchgram/client.py", line 83, in sync_history
    total_count = app.get_chat_history_count(uid)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/get_chat_history_count.py", line 58, in get_chat_history_count
    peer=await self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 87, in resolve_peer
    raise PeerIdInvalid
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it
```

- [x] 3. env 中需要指定 `BOT_ID` `TOKEN`，其实 `TOKEN` 是 `999999:xxxxxxxxxxxx`，包含了 `BOT_ID`，直接从 `TOKEN` 中提取更好。而且同时存在这两项造成了我的误解，以为 `TOKEN` 只需要冒号后面的部分

- [ ] 4. 增加：通过操作机器人下载历史消息，直接修改配置文件并重启容器不方便。如果能够指定范围下载历史消息就更好了。

- [x] 5. session 名称优化。目前程序登录之后，在 Telegram 设备记录里的设备类型是 `CPython 3.10.8`，设备名称是 `<API Short name> Pyrogram 2.0.59, Web Linux 5.15.63-0-virt`，无法适配到美观的设备图标，且这样使用 userbot 可能容易被封号（？）

**Comment by bennyzdog** [comment]
6. 支持定义容器名。主要应该是 mongo。三个容器名字分别叫 client、bot、mongo，还运行了其它程序时不容易区分，就想改名为 SearchGramClient、SearchGramBot、SearchGramMongo，如此一来，会因为容器名改变，互相无法连上。

**Comment by bennyzdog** [comment]
7. sync.ini 中的条目，会在消息拉取完成后被自动改为 false。如果程序最初拉取过历史消息，后面一直运行，理论上是没有问题的，消息都能完整记录。但考虑到，程序可能因为各种情况，程序停止了，再次启动运行时为 false 就不会进行同步，导致停止运行这期间缺少部分消息。

**Comment by BennyThink** [comment]
> * [ ]  6. 支持定义容器名。主要应该是 mongo。三个容器名字分别叫 client、bot、mongo，还运行了其它程序时不容易区分，就想改名为 SearchGramClient、SearchGramBot、SearchGramMongo，如此一来，会因为容器名改变，互相无法连上。

如果用docker-compose 跑，容器的名字应该是 `searchgram_bot_1` 类似这种的
