### ISSUE TITLE
client.py报错

### ISSUE THREAD

**Issue by MoshangUSA** [tgbot-collection/SearchGram#69]
不知道是哪里的问题，今天第一次尝试这个机器人。

按说明创建了API和bot，修改了`config.py`，然后运行`client.py`和`bot.py`。在`client.py`里面收到如下报错
```
[2023-01-03 16:19:17 dispatcher.py:253 E] localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
Traceback (most recent call last):
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/client.py", line 41, in message_handler
    tgdb.insert(data)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/engine.py", line 41, in insert
    resp = self.col.insert_one(doc)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 628, in insert_one
    self._insert_one(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 569, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
[2023-01-03 16:19:32 dispatcher.py:253 E] localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
Traceback (most recent call last):
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/client.py", line 56, in message_edit_handler
    tgdb.edit(cond, body)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/engine.py", line 46, in edit
    self.col.update_one(condition, {"$rename": {"text": "old_text.{}".format(body["edit_date"])}})
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 1041, in update_one
    self._update_retryable(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 836, in _update_retryable
    return self.__database.client._retryable_write(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
[2023-01-03 16:20:17 dispatcher.py:253 E] localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
Traceback (most recent call last):
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/client.py", line 41, in message_handler
    tgdb.insert(data)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/engine.py", line 41, in insert
    resp = self.col.insert_one(doc)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 628, in insert_one
    self._insert_one(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 569, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
[2023-01-03 16:22:42 dispatcher.py:253 E] localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
Traceback (most recent call last):
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/client.py", line 41, in message_handler
    tgdb.insert(data)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/engine.py", line 41, in insert
    resp = self.col.insert_one(doc)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 628, in insert_one
    self._insert_one(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 569, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
[2023-01-03 16:24:07 dispatcher.py:253 E] localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
Traceback (most recent call last):
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/client.py", line 41, in message_handler
    tgdb.insert(data)
  File "/Users/quarkquartet/Work/telegram-search/searchgram/engine.py", line 41, in insert
    resp = self.col.insert_one(doc)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 628, in insert_one
    self._insert_one(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/collection.py", line 569, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/Users/quarkquartet/envs/base/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 63b49bba7960577dc012fbc0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>
```
看上去没有成功和mangod建立链接。我不熟悉mangod，不知道这个是哪里的问题？

**Comment by MoshangUSA** [comment]
> 对的，你需要在本机上启动mongodb.看你像是macOS 那么 https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/

感谢回复。
